#
# Component Makefile
#
COMPONENT_ADD_INCLUDEDIRS :=include include/pjlib-util

COMPONENT_SRCDIRS :=src/pjlib-util

CFLAGS +=-D_POSIX_THREAD_PRIORITY_SCHEDULING -DPJ_HAS_SETJMP_H -DPJ_HAS_STRING_H \
        -DPJ_HAS_TIME_H
CPPFLAGS +=-D_POSIX_THREAD_PRIORITY_SCHEDULING -DPJ_HAS_SETJMP_H -DPJ_HAS_STRING_H \
        -DPJ_HAS_TIME_H